server:
  port: 9000
spring:
  application:
    name: character
  data:
    mongodb:
      host: localhost
      port: 27017
      username: travel
      password: '123456'
      authentication-database: travel
      database: character
      grid-fs-database: character
      repositories:
        enabled: true
